version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup
          command: |
            ./setup.sh
      - run:
          name: Tests
          command: |
            python3 -m unittest tests/flask_tests.py
            python3 -m unittest tests/module_tests.py
            python3 -m unittest tests/inference_tests.py
      - store_artifacts:
          path: test-reports/
          destination: NBA-Search